name: Deploy LEMP & Python App

on:
  push:
    branches:
      - master # Runs on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/MyMacrosTest
            git pull origin master
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install Python dependencies
            sudo systemctl restart nginx  # Restart Nginx
            sudo systemctl restart your-app  # Restart your Python app (Gunicorn, Flask, or Django)
